### PR TITLE
Fix cache dir on windows 

### PR DESCRIPTION
**Pull request by assignUser**
Closes #129

I just replaced `file.path` in `on.load` to see if this fixes the issue. 

If it does I think it would make sense to use {fs} throughout the package for consistency?

### CODE REVIEW

**Comment by mpadge** [comment]
@assignUser you also need to make the same change in the failing test itself:
https://github.com/ropensci-review-tools/pkgcheck/blob/7fd0b1e9716b4409f67695b6ed1915574699269d/tests/testthat/test-extra-checks.R#L10-L13

**Comment by mpadge** [comment]
No wait, I think it's actually caused by [this line in `pkgstats`](https://github.com/ropensci-review-tools/pkgstats/blob/b94328c6f0cc80f85b6b299d4640fd15e78f555b/R/extract_tarball.R#L41), although it works perfectly within the actual `pkgstats` repo, including on all windows tests. [These `pkgstats` test lines](https://github.com/ropensci-review-tools/pkgstats/blob/b94328c6f0cc80f85b6b299d4640fd15e78f555b/tests/testthat/test-pkgstats.R#L7-L11) do exactly the same thing as the problem lines here:
https://github.com/ropensci-review-tools/pkgcheck/blob/7fd0b1e9716b4409f67695b6ed1915574699269d/tests/testthat/test-extra-checks.R#L15-L16
yet they work in `pkgstats`, but fail when called here. I'll keep digging ...

**Comment by assignUser** [comment]
@mpadge but only if it works :wink:

**Comment by assignUser** [comment]
@mpadge oh, hmm Ok I'll fix the dispatch action in the mean time...

**Comment by mpadge** [comment]
Yeah, it can't actually be `file.path` at all, nor the `cache_dir`. The lines where it fails extract a tarball that is bundled with this package, and dump it into the `tempdir()`. The windows failure is because of inability to find the resultant sub-directory of `tempdir()`. I suspect this might have something to do with the `withr::` calls, but don't know yet. I'll find some more time tomorrow to check further

**Comment by mpadge** [comment]
@assignUser I adopted `fs` paths throughout whole pkg today, but it still didn't fix the windows cache path problems. I'll try next week(ish) on a windows machine to dig further. In the meantime I think we can close this PR now right?

**Comment by assignUser** [comment]
agreed :)

**Pull request closed without merging**
