### PR TITLE
Add use_github_check

### LINKED ISSUE #62: github workflow for others to run pkgcheck
Directly inspired by [`riskmetric` discussion](https://github.com/pharmaR/riskmetric/issues/224), develop a workflow for others to put in their own repos and run `pkgcheck` on GitHub runners. One of the biggest challenges would be working out an appropriate venue to push and host the HTML results. Current workflow in [`roreviewapi`](https://github.com/ropensci-review-tools/roreviewapi) only works because it is the bot making the calls, and the bot has admin privileges. It would likely be necessary for individual use to push to a `static/pkgcheck` directory on `gh-pages` branch, and to instruct users beforehand to switch on gh-pages. All could be checked in workflow anyway, and only pushed + served if branch exists. Ping @dgkf

### LINKED ISSUE #94: Copy post_to_issue fn from roreviewapi
So checks can be run either locally or on Github (#62) and results dumped in a specified issue. Also need for that a fn like there to match git user to authorised repos,  and only enable dumping in such.

### PR DESCRIPTION
**Pull request by assignUser**
Closes #62 
Closes #94 

I added the function and documentation with a link to the action repo. 
As suggested I also added myself as `aut` I hope that's ok :)

I haven't added any tests as I was not sure what your policy is with the non-standard structure of your `tests/testthat` dir.

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks @assignUser. I just pushed one commit here which adds a couple more input checks, but mostly just rearranges a bit so that ll input checks come prior to implementing any actual code. I'm going to check out all functionality on a test repo now, and expect to merge straight after that. As for tests, rather than "non-standard structure," it is a new structure introduced with [testthat v3.0](https://www.tidyverse.org/blog/2020/10/testthat-3-0-0/) and [testthat v3.1](https://www.tidyverse.org/blog/2021/10/testthat-3-1/) which add snapshot functionality. The `tests` directory contains several "snapshots" of expected `.md` output from `pkgcheck`. The `use_github_check` function will also generate output for which I'll add an additional test function with `expect_snapshot` for the output generated in the nominated `dir` - unless you want to do that by way of familiarising yourself with snapshots? Let me know, and I won't merge until I hear from you whether you want to do that or not? Thanks!

**Review by mpadge — CHANGES_REQUESTED** [review]
@assignUser In addition to [the question i put in the main thread](https://github.com/ropensci-review-tools/pkgcheck/pull/125#issuecomment-1019892358), we also need to rename the main function. There will likely be (many?) more packages introducing new workflow files, and it will be important for each to have unique names, and ideally to converge on some kind of vaguely standardised form at some stage. The `use_` prefix is already sufficiently standardised through `usethis`. [The associated functions in that package all have the format `use_github_action_...`](https://usethis.r-lib.org/reference/index.html#git-and-github), so I suggest we follow suit. That would give us `use_github_action_pkgcheck()` as a function name. Could you please update that? Thanks

**Comment by assignUser** [comment]
@mpadge Ah yeah that makes sense, fail fast etc. I do know snapshots we use [cli::test_that_cli](https://cli.r-lib.org/reference/test_that_cli.html) in {touchstone} an it's great (unless you work on a windows machine an can't reproduce the fancy snapshots with color correctly :facepalm:). 

I was more refering to this repo not having 1:1 relation between files in `R/` and `tests/testthat` as is recommended or at least implied [here](https://devtools.r-lib.org/reference/test.html) but I see how thematic/functional grouping of tests would also make sense.

**Comment by assignUser** [comment]
@mpadge I updated the name, I'll create a test now

**Comment by assignUser** [comment]
@mpadge I see you don't want to create the die if it does not exists? This will force users that do not use any other actions to manually create them and then run this again...

Which I don't think is inline with the intent of the use_* functions.

**Comment by mpadge** [comment]
> @mpadge I see you don't want to create the die if it does not exists? This will force users that do not use any other actions to manually create them and then run this again...

> Which I don't think is inline with the intent of the use_* functions.

fair enough; the above commit reverts back to `create.dir` instead. Thanks

**Comment by mpadge** [comment]
@assignUser All seems good now except for [checks on macOS which give errors](https://github.com/ropensci-review-tools/pkgcheck/runs/4921879245?check_suite_focus=true) like these:
```
- "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpPCfQ7Q/working_dir/Rtmp9s71fg/pkgcheck12c93db6086e/.github/pkgcheck.yaml"
+ "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpPCfQ7Q/working_dir/Rtmp9s71fg/pkgcheck12c93db6086e/.github/pkgcheck.yaml"
── Failure (test-github.R:18:1): use_github_action_pkgcheck [plain] ────────────
use_github_action_pkgcheck(dir = dir, overwrite = TRUE) (`actual`) not equal to `path` (`expected`).
```
All comes from these lines:
https://github.com/ropensci-review-tools/pkgcheck/blob/a57ec23272ccaee80d5477ce0c3562e93ef2425e/tests/testthat/test-github.R#L15-L20
because these two:
``` r
dir <- file.path(tempdir(),basename(tempfile("pkgcheck")), ".github")
# ...
path <- file.pah(dir, "pkgcheck.yaml")
```
gives the expected path, but when it's actually created on the GitHub runners on macOS, it has a  `private/` prepended at the start. Best solution is probably just to modify the actual problematic lines:
https://github.com/ropensci-review-tools/pkgcheck/blob/a57ec23272ccaee80d5477ce0c3562e93ef2425e/tests/testthat/test-github.R#L17-L18
To something like:
``` r
# macOS GitHub runners append "/private" to paths when they are actually created:
gha_path <-  gsub ("^\\/private", "", use_github_action_pkgcheck(dir = dir))
expect_equal(gha_path, path)
```
Do you wanna take care of that?

**Comment by assignUser** [comment]
@mpadge We had that issue with touchstone to, I don't remember what the fix was off the top of my head... I''ll see if I can find it

**Comment by assignUser** [comment]
@mpadge Couldn't find our fix quickly so I just implemented the regex version :D

**Comment by mpadge** [comment]
> @mpadge Couldn't find our fix quickly so I just implemented the regex version :D

Let me know if you do find it, please :wink: because this is getting pretty hacky - the constructed path also has a single `//`, whereas the expected one has single separators throughout. Easy to gsub away, but if you've got a better solution that'd be great!

**Pull request merged**
